"""upadate auth session and token tables

Revision ID: 12d963799c5d
Revises: 4636292cf99b
Create Date: 2025-08-31 12:39:37.609267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '12d963799c5d'
down_revision: Union[str, Sequence[str], None] = '4636292cf99b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.alter_column('deviceauthtoken', 'token_hash',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.drop_index(op.f('ix_deviceauthtoken_token_hash'), table_name='deviceauthtoken')
    op.create_index(op.f('ix_deviceauthtoken_token_hash'), 'deviceauthtoken', ['token_hash'], unique=True)
    op.drop_constraint(op.f('deviceauthtoken_user_id_fkey'), 'deviceauthtoken', type_='foreignkey')
    op.create_foreign_key('deviceauthtoken_user_id_fkey', 'deviceauthtoken', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('devicesession', 'session_token_hash',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=128),
               existing_nullable=False)
    op.alter_column('devicesession', 'device_fingerprint_hash',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=128),
               existing_nullable=True)
    op.drop_constraint(op.f('user_email_key'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
