"""update checkout session partial index uq_checkout_active_cart

Revision ID: 169348db3e45
Revises: 4bb9f4be5dc2
Create Date: 2025-10-12 15:57:39.482127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '169348db3e45'
down_revision: Union[str, Sequence[str], None] = '4bb9f4be5dc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('checkoutsession', 'status')
   
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
   
    op.add_column('checkoutsession', sa.Column('status', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
