"""add paymentwebhookevent schema

Revision ID: 20190b6300c4
Revises: d33800a5d9d2
Create Date: 2025-10-10 22:18:54.878454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20190b6300c4'
down_revision: Union[str, Sequence[str], None] = 'd33800a5d9d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paymentwebhookevent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=True),
    sa.Column('provider_event_id', sa.String(length=128), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paymentwebhookevent_processed_at'), 'paymentwebhookevent', ['processed_at'], unique=False)
    op.create_index(op.f('ix_paymentwebhookevent_provider_event_id'), 'paymentwebhookevent', ['provider_event_id'], unique=False)
    
    op.drop_index(op.f('ix_payment_provider_payment_id'), table_name='payment')
    op.create_unique_constraint(None, 'payment', ['provider_payment_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payment', type_='unique')
    op.create_index(op.f('ix_payment_provider_payment_id'), 'payment', ['provider_payment_id'], unique=True)
   
    op.drop_index(op.f('ix_paymentwebhookevent_provider_event_id'), table_name='paymentwebhookevent')
    op.drop_index(op.f('ix_paymentwebhookevent_processed_at'), table_name='paymentwebhookevent')
    op.drop_table('paymentwebhookevent')
    # ### end Alembic commands ###
