"""add attempts to ProviderWebhookEvent

Revision ID: 221d286f97e1
Revises: c2b7a7d37040
Create Date: 2025-09-27 13:20:07.572839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '221d286f97e1'
down_revision: Union[str, Sequence[str], None] = 'c2b7a7d37040'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.add_column('providerwebhookevent', sa.Column('attempts', sa.Integer(), nullable=True))
    op.alter_column('providerwebhookevent', 'provider',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('providerwebhookevent', 'provider',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('providerwebhookevent', 'attempts')
   
    # ### end Alembic commands ###
