"""add status to idempotency key table

Revision ID: 28f3f0d69a07
Revises: bf7da67b4b25
Create Date: 2025-11-06 22:37:17.571826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28f3f0d69a07'
down_revision: Union[str, Sequence[str], None] = 'bf7da67b4b25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.add_column('idempotencykey', sa.Column('status', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('idempotencykey', 'status')

    # ### end Alembic commands ###
