"""remove owner_id from imagecontent

Revision ID: 30391ecae7f8
Revises: 221d286f97e1
Create Date: 2025-09-27 14:59:56.785010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30391ecae7f8'
down_revision: Union[str, Sequence[str], None] = '221d286f97e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
   
    op.drop_index(op.f('ix_imagecontent_owner_id'), table_name='imagecontent')
    op.drop_constraint(op.f('imagecontent_owner_id_fkey'), 'imagecontent', type_='foreignkey')
    op.drop_column('imagecontent', 'owner_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('imagecontent', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('imagecontent_owner_id_fkey'), 'imagecontent', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_imagecontent_owner_id'), 'imagecontent', ['owner_id'], unique=False)
   
    # ### end Alembic commands ###
