"""checkout constraint fix

Revision ID: 33a211bdeb7c
Revises: 169348db3e45
Create Date: 2025-10-13 23:05:17.393198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33a211bdeb7c'
down_revision: Union[str, Sequence[str], None] = '169348db3e45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checkoutsession', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.create_index('uq_checkout_active_cart', 'checkoutsession', ['user_id'], unique=True,
                    postgresql_where=sa.text('is_active = true'))
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_checkout_active_cart', table_name='checkoutsession')
    op.drop_column('checkoutsession', 'is_active')
    # ### end Alembic commands ###
