"""InventoryReservation unique constraint on product and checkout id , remove individual indexes

Revision ID: 34d4cf7bec13
Revises: 62ef26213f6d
Create Date: 2025-10-07 17:32:14.747713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34d4cf7bec13'
down_revision: Union[str, Sequence[str], None] = '62ef26213f6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
   
    op.add_column('inventoryreservation', sa.Column('checkout_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_inventoryreservation_checkout_session_id'), table_name='inventoryreservation')
    op.drop_index(op.f('ix_inventoryreservation_product_id'), table_name='inventoryreservation')
    op.create_unique_constraint('uq_checkout_product', 'inventoryreservation', ['checkout_id', 'product_id'])
    op.drop_column('inventoryreservation', 'checkout_session_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventoryreservation', sa.Column('checkout_session_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint('uq_checkout_product', 'inventoryreservation', type_='unique')
    op.create_index(op.f('ix_inventoryreservation_product_id'), 'inventoryreservation', ['product_id'], unique=False)
    op.create_index(op.f('ix_inventoryreservation_checkout_session_id'), 'inventoryreservation', ['checkout_session_id'], unique=False)
    op.drop_column('inventoryreservation', 'checkout_id')
    # ### end Alembic commands ###
