"""make cart id on delete cascade

Revision ID: 41646b24ac62
Revises: bad278474755
Create Date: 2025-10-03 22:15:22.049808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41646b24ac62'
down_revision: Union[str, Sequence[str], None] = 'bad278474755'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('cartitem_cart_id_fkey'), 'cartitem', type_='foreignkey')
    op.create_foreign_key(None, 'cartitem', 'cart', ['cart_id'], ['id'], ondelete='CASCADE')
   
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_constraint(None, 'cartitem', type_='foreignkey')
    op.create_foreign_key(op.f('cartitem_cart_id_fkey'), 'cartitem', 'cart', ['cart_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
