"""create outbox event table and modify payment webhook event table

Revision ID: 4b83651788e9
Revises: 28f3f0d69a07
Create Date: 2025-11-08 23:25:37.375022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b83651788e9'
down_revision: Union[str, Sequence[str], None] = '28f3f0d69a07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outboxevent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=128), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('aggregate_type', sa.String(length=64), nullable=True),
    sa.Column('aggregate_id', sa.Integer(), nullable=True),
    sa.Column('dedupe_key', sa.String(length=256), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedupe_key', 'topic', name='uq_outbox_key_topic')
    )
    
    op.add_column('paymentwebhookevent', sa.Column('status', sa.Integer(), nullable=False))
    op.add_column('paymentwebhookevent', sa.Column('attempts', sa.Integer(), nullable=False))
    op.add_column('paymentwebhookevent', sa.Column('last_error', sa.String(length=1024), nullable=True))
    op.alter_column('paymentwebhookevent', 'provider',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.drop_index(op.f('ix_paymentwebhookevent_provider_event_id'), table_name='paymentwebhookevent')
    op.create_unique_constraint('uq_provider_event', 'paymentwebhookevent', ['provider', 'provider_event_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_provider_event', 'paymentwebhookevent', type_='unique')
    op.create_index(op.f('ix_paymentwebhookevent_provider_event_id'), 'paymentwebhookevent', ['provider_event_id'], unique=False)
    op.alter_column('paymentwebhookevent', 'provider',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.drop_column('paymentwebhookevent', 'last_error')
    op.drop_column('paymentwebhookevent', 'attempts')
    op.drop_column('paymentwebhookevent', 'status')
    op.drop_table('outboxevent')
    # ### end Alembic commands ###
