"""update checkout session partial index uq_checkout_active_cart

Revision ID: 4bb9f4be5dc2
Revises: 99ccf5b29f85
Create Date: 2025-10-12 15:44:55.379639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4bb9f4be5dc2'
down_revision: Union[str, Sequence[str], None] = '99ccf5b29f85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('checkoutsession', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
   
    op.add_column('checkoutsession', sa.Column('status', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('checkoutsession', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    # ### end Alembic commands ###
