"""add provider payment id to payment webhook event

Revision ID: 4e2185ccc4b1
Revises: 65d0e62e3bb3
Create Date: 2025-12-08 21:55:06.321546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e2185ccc4b1'
down_revision: Union[str, Sequence[str], None] = '65d0e62e3bb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.add_column('paymentwebhookevent', sa.Column('provider_payment_id', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paymentwebhookevent', 'provider_payment_id')
   
    # ### end Alembic commands ###
