"""update cacade delete cart session id & checkout session if non nullable

Revision ID: 51b44f14deac
Revises: a30ed17c62fa
Create Date: 2025-11-03 14:33:33.484187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51b44f14deac'
down_revision: Union[str, Sequence[str], None] = 'a30ed17c62fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('cart_session_id_fkey'), 'cart', type_='foreignkey')
    op.create_foreign_key(None, 'cart', 'devicesession', ['session_id'], ['id'], ondelete='CASCADE')
    op.alter_column('checkoutsession', 'session_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.alter_column('checkoutsession', 'session_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'cart', type_='foreignkey')
    op.create_foreign_key(op.f('cart_session_id_fkey'), 'cart', 'devicesession', ['session_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
