"""unique constraint on product name and owner_id

Revision ID: 59dcc8fe9422
Revises: fada620b607b
Create Date: 2025-09-18 00:06:23.580656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59dcc8fe9422'
down_revision: Union[str, Sequence[str], None] = 'fada620b607b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.create_unique_constraint('uq_product_name_owner_id', 'product', ['owner_id', 'name'])
 
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
   
    op.drop_constraint('uq_product_name_owner_id', 'product', type_='unique')
    
    # ### end Alembic commands ###
