"""create orders schema

Revision ID: 5bd854ed6dce
Revises: 41646b24ac62
Create Date: 2025-10-05 16:32:30.451020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bd854ed6dce'
down_revision: Union[str, Sequence[str], None] = '41646b24ac62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checkoutsession',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('cart_snapshot', sa.JSON(), nullable=True),
    sa.Column('selected_payment_method', sa.String(length=32), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checkoutsession_expires_at'), 'checkoutsession', ['expires_at'], unique=False)
    op.create_index(op.f('ix_checkoutsession_public_id'), 'checkoutsession', ['public_id'], unique=True)
    op.create_index(op.f('ix_checkoutsession_session_id'), 'checkoutsession', ['session_id'], unique=False)
    op.create_index(op.f('ix_checkoutsession_user_id'), 'checkoutsession', ['user_id'], unique=False)
    op.create_table('idempotencykey',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('owner_type', sa.String(length=32), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('request_hash', sa.String(length=128), nullable=True),
    sa.Column('response_code', sa.Integer(), nullable=True),
    sa.Column('response_body', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_idempotencykey_expires_at'), 'idempotencykey', ['expires_at'], unique=False)
    op.create_index(op.f('ix_idempotencykey_key'), 'idempotencykey', ['key'], unique=True)
    op.create_table('inventoryreservation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('checkout_session_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('reserved_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventoryreservation_checkout_session_id'), 'inventoryreservation', ['checkout_session_id'], unique=False)
    op.create_index(op.f('ix_inventoryreservation_order_id'), 'inventoryreservation', ['order_id'], unique=False)
    op.create_index(op.f('ix_inventoryreservation_product_id'), 'inventoryreservation', ['product_id'], unique=False)
    op.create_index(op.f('ix_inventoryreservation_reserved_until'), 'inventoryreservation', ['reserved_until'], unique=False)
    op.create_index(op.f('ix_inventoryreservation_status'), 'inventoryreservation', ['status'], unique=False)
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('subtotal', sa.BigInteger(), nullable=False),
    sa.Column('tax', sa.BigInteger(), nullable=False),
    sa.Column('shipping', sa.BigInteger(), nullable=False),
    sa.Column('discount', sa.BigInteger(), nullable=False),
    sa.Column('total', sa.BigInteger(), nullable=False),
    sa.Column('shipping_address_json', sa.JSON(), nullable=False),
    sa.Column('billing_address_json', sa.JSON(), nullable=True),
    sa.Column('payment_method', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('placed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delievered_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['devicesession.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_public_id'), 'order', ['public_id'], unique=True)
    op.create_index(op.f('ix_order_session_id'), 'order', ['session_id'], unique=False)
    op.create_index(op.f('ix_order_status'), 'order', ['status'], unique=False)
    op.create_index(op.f('ix_order_user_id'), 'order', ['user_id'], unique=False)
    op.create_table('orderitem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=128), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price_snapshot', sa.BigInteger(), nullable=False),
    sa.Column('tax_snapshot', sa.BigInteger(), nullable=True),
    sa.Column('discount_snapshot', sa.BigInteger(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id', 'product_id', name='uq_order_product')
    )
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_table('orderitem')
    op.drop_index(op.f('ix_order_user_id'), table_name='order')
    op.drop_index(op.f('ix_order_status'), table_name='order')
    op.drop_index(op.f('ix_order_session_id'), table_name='order')
    op.drop_index(op.f('ix_order_public_id'), table_name='order')
    op.drop_table('order')
    op.drop_index(op.f('ix_inventoryreservation_status'), table_name='inventoryreservation')
    op.drop_index(op.f('ix_inventoryreservation_reserved_until'), table_name='inventoryreservation')
    op.drop_index(op.f('ix_inventoryreservation_product_id'), table_name='inventoryreservation')
    op.drop_index(op.f('ix_inventoryreservation_order_id'), table_name='inventoryreservation')
    op.drop_index(op.f('ix_inventoryreservation_checkout_session_id'), table_name='inventoryreservation')
    op.drop_table('inventoryreservation')
    op.drop_index(op.f('ix_idempotencykey_key'), table_name='idempotencykey')
    op.drop_index(op.f('ix_idempotencykey_expires_at'), table_name='idempotencykey')
    op.drop_table('idempotencykey')
    op.drop_index(op.f('ix_checkoutsession_user_id'), table_name='checkoutsession')
    op.drop_index(op.f('ix_checkoutsession_session_id'), table_name='checkoutsession')
    op.drop_index(op.f('ix_checkoutsession_public_id'), table_name='checkoutsession')
    op.drop_index(op.f('ix_checkoutsession_expires_at'), table_name='checkoutsession')
    op.drop_table('checkoutsession')
    # ### end Alembic commands ###
