"""modify payments and orders related schemas

Revision ID: 5c44ef7b953b
Revises: a7c7667cd0c5
Create Date: 2025-11-15 23:56:10.149726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c44ef7b953b'
down_revision: Union[str, Sequence[str], None] = 'a7c7667cd0c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cart_session_id'), table_name='cart')
    op.create_unique_constraint(None, 'cart', ['session_id'])
    op.drop_index(op.f('ix_checkoutsession_session_id'), table_name='checkoutsession')
    
    op.drop_constraint(op.f('uq_commitintent_aggid_type_reason'), 'commitintent', type_='unique')
    op.create_unique_constraint('uq_commitintent_reason_agtype_agid', 'commitintent', ['reason', 'aggregate_type', 'aggregate_id'])
    
    op.create_index(op.f('ix_idempotencykey_status'), 'idempotencykey', ['status'], unique=False)
    op.drop_index(op.f('ix_inventoryreservation_order_id'), table_name='inventoryreservation')
    op.drop_index(op.f('ix_inventoryreservation_reserved_until'), table_name='inventoryreservation')
    op.drop_index(op.f('ix_inventoryreservation_status'), table_name='inventoryreservation')
    op.drop_constraint(op.f('uq_checkout_product'), 'inventoryreservation', type_='unique')
    op.create_unique_constraint('uq_product_checkout', 'inventoryreservation', ['product_id', 'checkout_id'])
    op.drop_index(op.f('ix_orders_session_id'), table_name='orders')
    op.drop_constraint(op.f('orders_provider_order_id_key'), 'orders', type_='unique')
    op.drop_constraint(op.f('uq_outboxevent_aggid_type_topic'), 'outboxevent', type_='unique')
    op.create_unique_constraint('uq_outboxevent_topic_agtype_agid', 'outboxevent', ['topic', 'aggregate_type', 'aggregate_id'])
    op.drop_constraint(op.f('payment_provider_order_id_key'), 'payment', type_='unique')
    op.drop_constraint(op.f('payment_provider_payment_id_key'), 'payment', type_='unique')
    op.create_unique_constraint('uq_provider_providerorder', 'payment', ['provider', 'provider_order_id'])
    op.create_unique_constraint('uq_provider_providerpayment', 'payment', ['provider', 'provider_payment_id'])
    op.drop_index(op.f('ix_paymentattempt_provider_event_id'), table_name='paymentattempt')
    op.drop_column('paymentattempt', 'provider_event_id')
    op.drop_index(op.f('ix_paymentwebhookevent_processed_at'), table_name='paymentwebhookevent')
    op.drop_index(op.f('ix_paymentwebhookevent_provider'), table_name='paymentwebhookevent')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_paymentwebhookevent_provider'), 'paymentwebhookevent', ['provider'], unique=False)
    op.create_index(op.f('ix_paymentwebhookevent_processed_at'), 'paymentwebhookevent', ['processed_at'], unique=False)
    op.add_column('paymentattempt', sa.Column('provider_event_id', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_paymentattempt_provider_event_id'), 'paymentattempt', ['provider_event_id'], unique=False)
    op.drop_constraint('uq_provider_providerpayment', 'payment', type_='unique')
    op.drop_constraint('uq_provider_providerorder', 'payment', type_='unique')
    op.create_unique_constraint(op.f('payment_provider_payment_id_key'), 'payment', ['provider_payment_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('payment_provider_order_id_key'), 'payment', ['provider_order_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('uq_outboxevent_topic_agtype_agid', 'outboxevent', type_='unique')
    op.create_unique_constraint(op.f('uq_outboxevent_aggid_type_topic'), 'outboxevent', ['aggregate_id', 'aggregate_type', 'topic'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('orders_provider_order_id_key'), 'orders', ['provider_order_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_orders_session_id'), 'orders', ['session_id'], unique=False)
    op.drop_constraint('uq_product_checkout', 'inventoryreservation', type_='unique')
    op.create_unique_constraint(op.f('uq_checkout_product'), 'inventoryreservation', ['checkout_id', 'product_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_inventoryreservation_status'), 'inventoryreservation', ['status'], unique=False)
    op.create_index(op.f('ix_inventoryreservation_reserved_until'), 'inventoryreservation', ['reserved_until'], unique=False)
    op.create_index(op.f('ix_inventoryreservation_order_id'), 'inventoryreservation', ['order_id'], unique=False)
    op.drop_index(op.f('ix_idempotencykey_status'), table_name='idempotencykey')
    
    op.drop_constraint('uq_commitintent_reason_agtype_agid', 'commitintent', type_='unique')
    op.create_unique_constraint(op.f('uq_commitintent_aggid_type_reason'), 'commitintent', ['aggregate_id', 'aggregate_type', 'reason'], postgresql_nulls_not_distinct=False)
  
    op.create_index(op.f('ix_checkoutsession_session_id'), 'checkoutsession', ['session_id'], unique=False)
    op.drop_constraint(None, 'cart', type_='unique')
    op.create_index(op.f('ix_cart_session_id'), 'cart', ['session_id'], unique=True)
    # ### end Alembic commands ###
