"""order add provider order id

Revision ID: 5d9249b804b4
Revises: 33a211bdeb7c
Create Date: 2025-10-14 10:57:31.651735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d9249b804b4'
down_revision: Union[str, Sequence[str], None] = '33a211bdeb7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.add_column('order', sa.Column('provider_order_id', sa.String(length=128), nullable=True))
    op.create_unique_constraint(None, 'order', ['provider_order_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order', type_='unique')
    op.drop_column('order', 'provider_order_id')
    
    # ### end Alembic commands ###
