"""checkout table modifications

Revision ID: 62ef26213f6d
Revises: 8c5ea9794300
Create Date: 2025-10-07 16:01:10.956455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62ef26213f6d'
down_revision: Union[str, Sequence[str], None] = '8c5ea9794300'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checkoutsession', sa.Column('status', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_checkoutsession_user_id'), table_name='checkoutsession')
    op.create_index('uq_checkout_active_cart', 'checkoutsession', ['user_id'], unique=True, postgresql_where=sa.text('status = 0'))
   
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_checkout_active_cart', table_name='checkoutsession', postgresql_where=sa.text('status = 0'))
    op.create_index(op.f('ix_checkoutsession_user_id'), 'checkoutsession', ['user_id'], unique=False)
    op.drop_column('checkoutsession', 'status')
    # ### end Alembic commands ###
