"""chnage index on provider provider venet id where event id non null (payment webhook)

Revision ID: 65d0e62e3bb3
Revises: be4f795acdfd
Create Date: 2025-12-08 20:34:43.912052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65d0e62e3bb3'
down_revision: Union[str, Sequence[str], None] = 'be4f795acdfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_provider_event'), 'paymentwebhookevent', type_='unique')
    op.create_index('uq_provider_event', 'paymentwebhookevent', ['provider', 'provider_event_id'], unique=True, postgresql_where=sa.text('provider_event_id IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_provider_event', table_name='paymentwebhookevent', postgresql_where=sa.text('provider_event_id IS NOT NULL'))
    op.create_unique_constraint(op.f('uq_provider_event'), 'paymentwebhookevent', ['provider', 'provider_event_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
