"""add uniqueness on user id and session id in cart

Revision ID: 6db8e701bec2
Revises: ad81e16d8089
Create Date: 2025-10-01 16:26:45.706119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6db8e701bec2'
down_revision: Union[str, Sequence[str], None] = 'ad81e16d8089'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cart_session_id'), table_name='cart')
    op.create_index(op.f('ix_cart_session_id'), 'cart', ['session_id'], unique=True)
    op.drop_index(op.f('ix_cart_user_id'), table_name='cart')
    op.create_index(op.f('ix_cart_user_id'), 'cart', ['user_id'], unique=True)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_index(op.f('ix_cart_user_id'), table_name='cart')
    op.create_index(op.f('ix_cart_user_id'), 'cart', ['user_id'], unique=False)
    op.drop_index(op.f('ix_cart_session_id'), table_name='cart')
    op.create_index(op.f('ix_cart_session_id'), 'cart', ['session_id'], unique=False)
    # ### end Alembic commands ###
