"""update indexes

Revision ID: 784f17aaae55
Revises: 8f88d6a04818
Create Date: 2025-09-12 22:23:45.957711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '784f17aaae55'
down_revision: Union[str, Sequence[str], None] = '8f88d6a04818'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_deviceauthtoken_token_hash", table_name="deviceauthtoken")

    # Create partial index on device_auth_token(token_hash) for active tokens
    op.create_index(
        "idx_deviceauthtoken_tokenhash_active",
        "deviceauthtoken",
        ["token_hash"],
        postgresql_where=sa.text("revoked_at IS NULL")
    )

    # Create partial index on users(email) for active users (not deleted)
    op.create_index(
        "idx_users_email_active",
        "users",
        ["email"],
        postgresql_where=sa.text("deleted_at IS NULL")
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_users_email_active", table_name="users")
    op.drop_index("idx_deviceauthtoken_tokenhash_active", table_name="deviceauthtoken")

    # Recreate previous full indices (names assumed; change if different)
    op.create_index(
        "ix_deviceauthtoken_token_hash",
        "deviceauthtoken",
        ["token_hash"],
    )

    # ### end Alembic commands ###
