"""schema reanalysis changes and uploadwebhook table recreate,test db so data migration not kept in mind for this  migration

Revision ID: 813e9a7e41a9
Revises: 5c44ef7b953b
Create Date: 2025-11-25 22:44:15.117337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '813e9a7e41a9'
down_revision: Union[str, Sequence[str], None] = '5c44ef7b953b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploadswebhookevent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_event_id', sa.String(length=1000), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_event_id')
    )
    op.drop_table('providerwebhookevent')
    op.drop_constraint(op.f('cart_session_id_key'), 'cart', type_='unique')
    op.drop_index(op.f('ix_cart_user_id'), table_name='cart')
    op.create_index('uq_cart_session_id', 'cart', ['session_id'], unique=True, postgresql_where=sa.text('session_id IS NOT NULL'))
    op.create_index('uq_cart_user_id', 'cart', ['user_id'], unique=True, postgresql_where=sa.text('user_id IS NOT NULL'))

    op.drop_index(op.f('idx_deviceauthtoken_tokenhash_active'), table_name='deviceauthtoken', postgresql_where='(revoked_at IS NULL)')
    op.create_index(op.f('ix_deviceauthtoken_token_hash'), 'deviceauthtoken', ['token_hash'], unique=True)
    op.alter_column('devicesession', 'public_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('devicesession', 'session_expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.add_column('imagecontent', sa.Column('provider', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('imagecontent', 'provider')
    op.alter_column('devicesession', 'session_expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('devicesession', 'public_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_deviceauthtoken_token_hash'), table_name='deviceauthtoken')
    op.create_index(op.f('idx_deviceauthtoken_tokenhash_active'), 'deviceauthtoken', ['token_hash'], unique=False, postgresql_where='(revoked_at IS NULL)')
   
    op.drop_index('uq_cart_user_id', table_name='cart', postgresql_where=sa.text('user_id IS NOT NULL'))
    op.drop_index('uq_cart_session_id', table_name='cart', postgresql_where=sa.text('session_id IS NOT NULL'))
    op.create_index(op.f('ix_cart_user_id'), 'cart', ['user_id'], unique=True)
    op.create_unique_constraint(op.f('cart_session_id_key'), 'cart', ['session_id'], postgresql_nulls_not_distinct=False)
    op.create_table('providerwebhookevent',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('provider_event_id', sa.VARCHAR(length=1000), autoincrement=False, nullable=False),
    sa.Column('provider', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('received_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('processed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('attempts', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('providerwebhookevent_pkey')),
    sa.UniqueConstraint('provider_event_id', name=op.f('uq_providerwebhookevent_provider_event_id'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('uploadswebhookevent')
    # ### end Alembic commands ###
