"""update cechkout session user id non nullable

Revision ID: 8c5ea9794300
Revises: 5bd854ed6dce
Create Date: 2025-10-05 23:24:04.324319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c5ea9794300'
down_revision: Union[str, Sequence[str], None] = '5bd854ed6dce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('checkoutsession', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
   
    op.alter_column('checkoutsession', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
