"""add order id  to payment webhook event

Revision ID: 8f7ceef6e72d
Revises: 4e2185ccc4b1
Create Date: 2025-12-08 22:40:55.440174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f7ceef6e72d'
down_revision: Union[str, Sequence[str], None] = '4e2185ccc4b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
 
    op.add_column('paymentwebhookevent', sa.Column('order_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_paymentwebhookevent_order_id'), 'paymentwebhookevent', ['order_id'], unique=False)
    op.drop_column('paymentwebhookevent', 'provider_payment_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paymentwebhookevent', sa.Column('provider_payment_id', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_paymentwebhookevent_order_id'), table_name='paymentwebhookevent')
    op.drop_column('paymentwebhookevent', 'order_id')
  
    # ### end Alembic commands ###
