"""add usermedia

Revision ID: 8f88d6a04818
Revises: 12d963799c5d
Create Date: 2025-09-06 22:29:30.385550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8f88d6a04818'
down_revision: Union[str, Sequence[str], None] = '12d963799c5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usermedia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('profile_image_url', sa.String(length=1024), nullable=True),
    sa.Column('profile_image_thumb_url', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    
    op.drop_column('users', 'profile_image_url')
    op.drop_column('users', 'profile_image_thumb_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_image_thumb_url', sa.VARCHAR(length=1024), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('profile_image_url', sa.VARCHAR(length=1024), autoincrement=False, nullable=True))
    op.drop_table('usermedia')
    # ### end Alembic commands ###
