"""chnage uniqueness constraints on credential

Revision ID: 96397f3f833a
Revises: 66f7ee1d1e68
Create Date: 2025-12-14 19:38:57.029871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96397f3f833a'
down_revision: Union[str, Sequence[str], None] = '66f7ee1d1e68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('credential', 'provider',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.drop_constraint(op.f('uq_credential_user_type_provider'), 'credential', type_='unique')
    op.create_unique_constraint('uq_credential_user_provider', 'credential', ['user_id', 'provider'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_credential_user_provider', 'credential', type_='unique')
    op.create_unique_constraint(op.f('uq_credential_user_type_provider'), 'credential', ['user_id', 'type', 'provider'], postgresql_nulls_not_distinct=False)
    op.alter_column('credential', 'provider',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    # ### end Alembic commands ###
