"""add name field to users and address

Revision ID: 985e491d90ce
Revises: fbef4fd0439f
Create Date: 2025-08-30 15:31:06.518235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '985e491d90ce'
down_revision: Union[str, Sequence[str], None] = 'fbef4fd0439f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('name', sa.String(length=128), nullable=True))
 
    op.add_column('users', sa.Column('name', sa.String(length=128), nullable=True))
    
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_column('users', 'name')

    op.drop_column('address', 'name')
    # ### end Alembic commands ###
