"""update payment attempts schema

Revision ID: 99ccf5b29f85
Revises: 20190b6300c4
Create Date: 2025-10-11 19:33:36.240134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99ccf5b29f85'
down_revision: Union[str, Sequence[str], None] = '20190b6300c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paymentattempt', sa.Column('status', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_paymentwebhookevent_provider'), 'paymentwebhookevent', ['provider'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_paymentwebhookevent_provider'), table_name='paymentwebhookevent')
    op.drop_column('paymentattempt', 'status')
    # ### end Alembic commands ###
