"""add imagecontent table and chnages to productimage

Revision ID: 9b22228461ba
Revises: 06185d75b687
Create Date: 2025-09-20 20:07:57.292848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b22228461ba'
down_revision: Union[str, Sequence[str], None] = '06185d75b687'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imagecontent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(length=128), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('provider_public_id', sa.String(length=1024), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('checksum')
    )
    op.create_index(op.f('ix_imagecontent_owner_id'), 'imagecontent', ['owner_id'])
    op.create_index(op.f('ix_imagecontent_public_id'), 'imagecontent', ['public_id'], unique=True)
   
    op.add_column('productimage', sa.Column('content_id', sa.Integer(), nullable=False))
    op.add_column('productimage', sa.Column('storage_provider', sa.String(length=64), nullable=False))
    op.drop_constraint(op.f('productimage_checksum_key'), 'productimage', type_='unique')
    op.create_unique_constraint(None, 'productimage', ['storage_key'])
    op.create_foreign_key(None, 'productimage', 'imagecontent', ['content_id'], ['id'], ondelete='CASCADE')
    op.drop_column('productimage', 'checksum')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productimage', sa.Column('checksum', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'productimage', type_='foreignkey')
    op.drop_constraint(None, 'productimage', type_='unique')
    op.create_unique_constraint(op.f('productimage_checksum_key'), 'productimage', ['checksum'], postgresql_nulls_not_distinct=False)
    op.drop_column('productimage', 'storage_provider')
    op.drop_column('productimage', 'content_id')
   
    op.drop_index(op.f('ix_imagecontent_public_id'), table_name='imagecontent')
    op.drop_index(op.f('ix_imagecontent_owner_id'), table_name='imagecontent')
    op.drop_table('imagecontent')
    # ### end Alembic commands ###
