"""make content id in product image to be nullable

Revision ID: a07e0983d85b
Revises: 30391ecae7f8
Create Date: 2025-09-28 12:29:05.729089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a07e0983d85b'
down_revision: Union[str, Sequence[str], None] = '30391ecae7f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
   
    op.alter_column('productimage', 'content_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('providerwebhookevent', 'processed')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('providerwebhookevent', sa.Column('processed', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.alter_column('productimage', 'content_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
