"""add public id to devicesession as i key

Revision ID: a30ed17c62fa
Revises: 5219a19ae93d
Create Date: 2025-10-30 10:52:54.023878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a30ed17c62fa'
down_revision: Union[str, Sequence[str], None] = '5219a19ae93d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devicesession', sa.Column('public_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_devicesession_public_id'), 'devicesession', ['public_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_devicesession_public_id'), table_name='devicesession')
    op.drop_column('devicesession', 'public_id')
   
    # ### end Alembic commands ###
