"""make outbox agg id agge type and device session public id non nullable

Revision ID: a7c7667cd0c5
Revises: d31996c1dae4
Create Date: 2025-11-09 10:48:00.927756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7c7667cd0c5'
down_revision: Union[str, Sequence[str], None] = 'd31996c1dae4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.alter_column('outboxevent', 'aggregate_type',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('outboxevent', 'aggregate_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('outboxevent', 'aggregate_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('outboxevent', 'aggregate_type',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    
    # ### end Alembic commands ###
