"""make storage key nullable

Revision ID: a8a7a2c5656d
Revises: 9b22228461ba
Create Date: 2025-09-22 19:41:17.299159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8a7a2c5656d'
down_revision: Union[str, Sequence[str], None] = '9b22228461ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
   
    op.alter_column('productimage', 'storage_key',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('productimage', 'storage_key',
               existing_type=sa.VARCHAR(length=1024),
               nullable=False)
   
