"""add user_id to device_session & make cart session_id on delte set null

Revision ID: ad81e16d8089
Revises: e76c07f505a3
Create Date: 2025-10-01 14:04:31.271327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad81e16d8089'
down_revision: Union[str, Sequence[str], None] = 'e76c07f505a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('cart_session_id_fkey'), 'cart', type_='foreignkey')
    op.create_foreign_key(None, 'cart', 'devicesession', ['session_id'], ['id'], ondelete='SET NULL')
   
    op.add_column('devicesession', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_devicesession_user_id'), 'devicesession', ['user_id'], unique=False)
    op.create_foreign_key(None, 'devicesession', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'devicesession', type_='foreignkey')
    op.drop_index(op.f('ix_devicesession_user_id'), table_name='devicesession')
    op.drop_column('devicesession', 'user_id')
    
    op.drop_constraint(None, 'cart', type_='foreignkey')
    op.create_foreign_key(op.f('cart_session_id_fkey'), 'cart', 'devicesession', ['session_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
