"""add unique insertion anchor to orders table

Revision ID: ae550d964457
Revises: d1558250da25
Create Date: 2025-12-18 20:33:48.762202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae550d964457'
down_revision: Union[str, Sequence[str], None] = 'd1558250da25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('ik_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_orders_unq_ik_id'), 'orders', ['ik_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_unq_ik_id'), table_name='orders')
    op.drop_column('orders', 'ik_id')
    # ### end Alembic commands ###
