"""payment add provider order id

Revision ID: aeea1673d46a
Revises: 5d9249b804b4
Create Date: 2025-10-14 11:50:13.430324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aeea1673d46a'
down_revision: Union[str, Sequence[str], None] = '5d9249b804b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
   
    op.add_column('payment', sa.Column('provider_order_id', sa.String(length=128), nullable=True))
    op.create_unique_constraint(None, 'payment', ['provider_order_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payment', type_='unique')
    op.drop_column('payment', 'provider_order_id')
    
    # ### end Alembic commands ###
