"""update phone

Revision ID: b77be959fb9a
Revises: 78752127d410
Create Date: 2025-08-30 23:23:42.028383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b77be959fb9a'
down_revision: Union[str, Sequence[str], None] = '78752127d410'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userphone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=False,server_default=sa.func.now()),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False,server_default=sa.func.now()),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_index(op.f('ix_userphone_user_id'), 'userphone', ['user_id'], unique=False)
    
    op.create_unique_constraint(None, 'credential', ['password_hash'])
    op.create_unique_constraint(None, 'credential', ['provider_user_id'])
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_constraint(None, 'credential', type_='unique')
    op.drop_constraint(None, 'credential', type_='unique')
    op.drop_index(op.f('ix_userphone_user_id'), table_name='userphone')
    op.drop_table('userphone')
    # ### end Alembic commands ###
