"""add products schema

Revision ID: baa96f7c37bd
Revises: cc31f3b133b2
Create Date: 2025-09-15 23:45:33.338417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'baa96f7c37bd'
down_revision: Union[str, Sequence[str], None] = 'cc31f3b133b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productcategory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('stock_qty', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('base_price', sa.Integer(), nullable=False),
    sa.Column('specs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, default=None),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_owner_id'), 'product', ['owner_id'], unique=False)
    op.create_index(op.f('ix_product_public_id'), 'product', ['public_id'], unique=True)
    op.create_table('productcategorylink',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('prod_category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['prod_category_id'], ['productcategory.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'prod_category_id', name='uq_product_category')
    )
    op.create_index(op.f('ix_productcategorylink_prod_category_id'), 'productcategorylink', ['prod_category_id'], unique=False)
    op.create_index(op.f('ix_productcategorylink_product_id'), 'productcategorylink', ['product_id'], unique=False)
    op.create_table('productimage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('storage_key', sa.String(length=1024), nullable=False),
    sa.Column('bucket', sa.String(length=255), nullable=True),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('checksum', sa.String(length=128), nullable=True),
    sa.Column('variants', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('PENDING_UPLOADED', 'UPLOADED', 'PROCESSING', 'READY', 'FAILED', name='imageuploadstatus'), nullable=False,
              server_default='PENDING_UPLOADED'),
    sa.Column('orig_filename', sa.String(length=255), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('alt_text', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_productimage_product_id'), 'productimage', ['product_id'], unique=False)
    op.create_index(op.f('ix_productimage_public_id'), 'productimage', ['public_id'], unique=True)
   
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
   
    op.drop_index(op.f('ix_productimage_public_id'), table_name='productimage')
    op.drop_index(op.f('ix_productimage_product_id'), table_name='productimage')
    op.drop_table('productimage')
    op.drop_index(op.f('ix_productcategorylink_product_id'), table_name='productcategorylink')
    op.drop_index(op.f('ix_productcategorylink_prod_category_id'), table_name='productcategorylink')
    op.drop_table('productcategorylink')
    op.drop_index(op.f('ix_product_public_id'), table_name='product')
    op.drop_index(op.f('ix_product_owner_id'), table_name='product')
    op.drop_table('product')
    op.drop_table('productcategory')
    # ### end Alembic commands ###
