"""fix cart and user link plus remove cart item prioce snapshot

Revision ID: bad278474755
Revises: 6db8e701bec2
Create Date: 2025-10-03 15:04:14.635740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bad278474755'
down_revision: Union[str, Sequence[str], None] = '6db8e701bec2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cartitem', 'unit_price_snapshot')
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cartitem', sa.Column('unit_price_snapshot', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
