"""make provider event id nullable in payment webhooks & chnage status varieties for payment , order ,payment webhook

Revision ID: be4f795acdfd
Revises: 6f4bd48e4aeb
Create Date: 2025-12-08 20:31:16.847788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be4f795acdfd'
down_revision: Union[str, Sequence[str], None] = '6f4bd48e4aeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
   
    op.alter_column('paymentwebhookevent', 'provider_event_id',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('paymentwebhookevent', 'provider_event_id',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)

    # ### end Alembic commands ###
