"""make payment table order id unique

Revision ID: c0caf44a57d2
Revises: 8f7ceef6e72d
Create Date: 2025-12-08 22:56:32.799045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0caf44a57d2'
down_revision: Union[str, Sequence[str], None] = '8f7ceef6e72d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
  
    op.drop_index(op.f('ix_payment_order_id'), table_name='payment')
    op.create_unique_constraint(None, 'payment', ['order_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payment', type_='unique')
    op.create_index(op.f('ix_payment_order_id'), 'payment', ['order_id'], unique=False)
  
    # ### end Alembic commands ###
