"""add unique constraints in credential for only 1 cred per user of same type and provider+provider_user_id

Revision ID: cba69ff98159
Revises: 813e9a7e41a9
Create Date: 2025-12-07 16:24:48.508070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cba69ff98159'
down_revision: Union[str, Sequence[str], None] = '813e9a7e41a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
   
    op.create_unique_constraint('uq_credential_provider_userid', 'credential', ['provider', 'provider_user_id'])
    op.create_unique_constraint('uq_credential_user_type_provider', 'credential', ['user_id', 'type', 'provider'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_credential_user_type_provider', 'credential', type_='unique')
    op.drop_constraint('uq_credential_provider_userid', 'credential', type_='unique')
  
    # ### end Alembic commands ###
