"""add role version to users

Revision ID: cc31f3b133b2
Revises: d6349403285d
Create Date: 2025-09-14 16:46:47.478507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc31f3b133b2'
down_revision: Union[str, Sequence[str], None] = 'd6349403285d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role_version', sa.Integer(), nullable=False,
                                     server_default=sa.text('0')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
   
    op.drop_column('users', 'role_version')

    # ### end Alembic commands ###
