"""prod image content id unique index where not null

Revision ID: d1558250da25
Revises: 96397f3f833a
Create Date: 2025-12-17 13:02:25.080266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1558250da25'
down_revision: Union[str, Sequence[str], None] = '96397f3f833a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_product_image_content_id', 'productimage', ['content_id'], unique=True, postgresql_where=sa.text('content_id IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_product_image_content_id', table_name='productimage', postgresql_where=sa.text('content_id IS NOT NULL'))
    # ### end Alembic commands ###
