"""add checkout id fkey to ikey for mismatch identification

Revision ID: d22b12ed593c
Revises: ae550d964457
Create Date: 2025-12-21 10:16:08.586025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd22b12ed593c'
down_revision: Union[str, Sequence[str], None] = 'ae550d964457'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('idempotencykey', sa.Column('cs_id', sa.Integer(), nullable=False))
    op.create_foreign_key('fk_idempotencykey_cs_id', 'idempotencykey', 'checkoutsession', ['cs_id'], ['id'])
    op.drop_index(op.f('ix_orders_unq_ik_id'), table_name='orders')
    op.create_index(op.f('ix_orders_ik_id'), 'orders', ['ik_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_ik_id'), table_name='orders')
    op.create_index(op.f('ix_orders_unq_ik_id'), 'orders', ['ik_id'], unique=True)
    op.drop_constraint('fk_idempotencykey_cs_id', 'idempotencykey', type_='foreignkey')
    op.drop_column('idempotencykey', 'cs_id')
    # ### end Alembic commands ###
