"""change unique constraint of outbox

Revision ID: d31996c1dae4
Revises: 7723ee5b1391
Create Date: 2025-11-09 10:35:11.407936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd31996c1dae4'
down_revision: Union[str, Sequence[str], None] = '7723ee5b1391'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_constraint(op.f('uq_outbox_key_topic'), 'outboxevent', type_='unique')
    op.create_unique_constraint('uq_outboxevent_aggid_type_topic', 'outboxevent', ['aggregate_id', 'aggregate_type', 'topic'])
    # Drop the dedupe_key column
    op.drop_column('outboxevent', 'dedupe_key')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outboxevent', 
                  sa.Column('dedupe_key', sa.String(length=128), nullable=True))
    op.drop_constraint('uq_outboxevent_aggid_type_topic', 'outboxevent', type_='unique')
    op.create_unique_constraint(op.f('uq_outbox_key_topic'), 'outboxevent', ['dedupe_key', 'topic'], postgresql_nulls_not_distinct=False)
    
    # ### end Alembic commands ###
