"""add payment and p[aymentattempt schema

Revision ID: d33800a5d9d2
Revises: 34d4cf7bec13
Create Date: 2025-10-08 14:32:31.637540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd33800a5d9d2'
down_revision: Union[str, Sequence[str], None] = '34d4cf7bec13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=True),
    sa.Column('provider_payment_id', sa.String(length=128), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('pay_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_order_id'), 'payment', ['order_id'], unique=False)
    op.create_index(op.f('ix_payment_provider_payment_id'), 'payment', ['provider_payment_id'], unique=True)
    op.create_index(op.f('ix_payment_public_id'), 'payment', ['public_id'], unique=True)
    op.create_index(op.f('ix_payment_status'), 'payment', ['status'], unique=False)
    op.create_table('paymentattempt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('provider_response', sa.JSON(), nullable=True),
    sa.Column('provider_event_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payment.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paymentattempt_payment_id'), 'paymentattempt', ['payment_id'], unique=False)
    op.create_index(op.f('ix_paymentattempt_provider_event_id'), 'paymentattempt', ['provider_event_id'], unique=False)
   
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
   
    op.drop_index(op.f('ix_paymentattempt_provider_event_id'), table_name='paymentattempt')
    op.drop_index(op.f('ix_paymentattempt_payment_id'), table_name='paymentattempt')
    op.drop_table('paymentattempt')
    op.drop_index(op.f('ix_payment_status'), table_name='payment')
    op.drop_index(op.f('ix_payment_public_id'), table_name='payment')
    op.drop_index(op.f('ix_payment_provider_payment_id'), table_name='payment')
    op.drop_index(op.f('ix_payment_order_id'), table_name='payment')
    op.drop_table('payment')
    # ### end Alembic commands ###
