"""remove accidentally placed unique from product owner id 

Revision ID: e6c9eae03d91
Revises: a07e0983d85b
Create Date: 2025-09-28 23:30:56.834488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6c9eae03d91'
down_revision: Union[str, Sequence[str], None] = 'a07e0983d85b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
   
    op.drop_index(op.f('ix_product_owner_id'), table_name='product')
    op.create_index(op.f('ix_product_owner_id'), 'product', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_owner_id'), table_name='product')
    op.create_index(op.f('ix_product_owner_id'), 'product', ['owner_id'], unique=True)
   
    # ### end Alembic commands ###
