"""unique constraint on checksum

Revision ID: f0d1fdde3e6e
Revises: baa96f7c37bd
Create Date: 2025-09-16 00:00:49.741115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0d1fdde3e6e'
down_revision: Union[str, Sequence[str], None] = 'baa96f7c37bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_unique_constraint(None, 'productimage', ['checksum'])
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'productimage', type_='unique')
    # ### end Alembic commands ###
