"""make user id fkeys non nullable

Revision ID: fa33ae072ddc
Revises: 9c2c0d4d37b6
Create Date: 2025-08-30 18:18:48.202707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fa33ae072ddc'
down_revision: Union[str, Sequence[str], None] = '9c2c0d4d37b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('address', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('deviceauthtoken', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('deviceauthtoken', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('address', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
