"""unique constraint on product name and owner_id

Revision ID: fada620b607b
Revises: 25d460f457df
Create Date: 2025-08-30 18:18:48.202707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fada620b607b'
down_revision: Union[str, Sequence[str], None] = '25d460f457df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
   
    # ### end Alembic commands ###
